# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: python
virtualenv:
  system_site_packages: true
language: R
sudo: false
cache: packages

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

before_install:
  - sudo apt-get install -qq libgdal1h
  - sudo apt-get install -qq python-gdal

after_success:
    - Rscript -e 'covr::codecov()'
